baseurl: /
languageCode: en-US
title: Análsis de datos con software libre
theme: "Hugo-Octopress"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$

permalinks:
  post: /:day/:month/:year/:slug/

menu:
  main:
    - name: Objetivos
      url: /objetivos/
      weight: 10
    - name: Contenidos
      url: /contenidos/
      weight: 20
    - name: Presentación
      url: /presentacion/
      weight: 30
    - name: Modalidad de cursado
      url: /estrategia/
      weight: 40
    - name: Inscripción
      url: https://forms.gle/XB78pzJbXTRxSn8YA
      weight: 100
    
#    - name: GitHub
#      url: https://github.com/ebologna
#    - name: X
#      url: https://twitter.com/rstudio
#    - name: otro
#      url: https://ebologna.rbind.io/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  customCSS:
    - "css/custom.css"
  logo:
    alt: Logo
    height: 50
    url: /cinco.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
